Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    return next(matches).load()
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
ModuleNotFoundError: No module named 'graph2tac.transformer'
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
ModuleNotFoundError: No module named 'graph2tac.transformer'
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'graph2tac.transformer'
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
ModuleNotFoundError: No module named 'graph2tac.transformer'
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'graph2tac.transformer'
ModuleNotFoundError: No module named 'graph2tac.transformer'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
ModuleNotFoundError: No module named 'graph2tac.transformer'
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
ModuleNotFoundError: No module named 'graph2tac.transformer'
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'graph2tac.transformer'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'graph2tac.transformer'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'graph2tac.transformer'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    return next(matches).load()
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ModuleNotFoundError: No module named 'graph2tac.transformer'
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'graph2tac.transformer'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'graph2tac.transformer'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'graph2tac.transformer'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/tmp/tactician.tmp.Zbqinw/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'graph2tac.transformer'
File "./theories/Reals/Exp_prop.v", line 29, characters 2-35:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Rpower.v", line 33, characters 2-77:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Rgeom.v", line 25, characters 2-330:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Rtrigo_calc.v", line 20, characters 2-79:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Ranalysis4.v", line 26, characters 2-79:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Rtrigo_reg.v", line 24, characters 2-27:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/RiemannInt_SF.v", line 29, characters 2-50:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Ranalysis5.v", line 32, characters 2-74:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/NewtonInt.v", line 33, characters 2-314:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Ranalysis_reg.v", line 34, characters 0-9:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Ratan.v", line 31, characters 0-74:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Machin.v", line 34, characters 0-26:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/RiemannInt.v", line 48, characters 2-37:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Rtrigo1.v", line 35, characters 2-31:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/setoid_ring/Rings_R.v", line 19, characters 0-37:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

